### ISSUE TITLE
Ability to specify partition.assignment.strategy

### ISSUE THREAD

**Issue by erik-stephens** [terascope/kafka-assets#18]
Partition lag is usually due to some problem with the worker.  Adding workers or restarting the job doesn't help much with the default `range` strategy since the lagging partitions will still be assigned to a small subset of the workers.  Would like to be able to specify that on a per-job basis.  Or, maybe simpler to experiment with `roundrobin` and hard-code that setting if we don't want to expose it as a job option.

**Comment by kstaken** [comment]
Exposing this as an option is probably a good idea as it does seem `roundrobin` might be helpful in some cases.

Came across this which should be noted: https://github.com/edenhill/librdkafka/issues/2121
