### ISSUE TITLE
Dynamic routing

### ISSUE THREAD

**Issue by kstaken** [terascope/kafka-assets#258]
This feature will rely on the ability to create topics dynamically based on the incoming route. This is the default for Kafka but it's a common change to turn this feature off.

We'll use `**` in the route configuration to indicate that dynamic routing should be used. This is a special form of default route which means it only applies if other routes don't already match.

* Using `**` and `*` together in the same config should be considered an error. 
* Usage of `**` or `*` are optional.
* If the sender can not successfully create a dynamic topic if needs to provide a clear failure to the end user.
   * It may be worth looking into if it's possible to introspect this configuration from the cluster.

```
{
   "_op": "kafka_sender",
   "topic": "the-topic",
   "connection_map": {
      "sam": "kafka_cluster2",
      "ralph": "kafka_cluster3",
      "**": "kafka_cluster1"
   }
}
```

The configuration above would result in the following routes.

* standard:route:sam -> kafka_cluster2:the-topic-sam
* standard:route:ralph -> kafka_cluster3:the-topic-ralph
* standard:route:chuck -> kafka_cluster1:the-topic-chuck
* standard:route:joe -> kafka_cluster1:the-topic-joe
* standard:route:mary -> kafka_cluster1:the-topic-mary

In addition to this change here we also need to consider the impact of this on the `file` assets to make sure routing consistency is maintained.

**Comment by macgyver603** [comment]
The `file` assets use [this](https://github.com/terascope/file-assets/blob/da065449c627afd1d40cf222bfe0b90a8e1ff2de/asset/src/__lib/slice.ts#L31) batcher to sort records based on the `standard:route` if present on a record, so on changes will not be needed with that asset bundle.

**Comment by jsnoble** [comment]
This is an old ticket, routing is now only done through the routed_sender in the standard assets
