### ISSUE TITLE
Update node-rdkafka to v3.2.0

### ISSUE THREAD

**Issue by godber** [terascope/kafka-assets#869]
We should update to this:

https://github.com/Blizzard/node-rdkafka/releases/tag/v3.2.0

It in turn updates to `librdkafka` 2.6.0: https://github.com/Blizzard/node-rdkafka/pull/1103

We should bump the minor version on our asset and make sure to update the terafoundation_kafka_connector version in the base image.

**Comment by godber** [comment]
On question we need to answer is how is this cooperative rebalance behavior triggered, then we need to test whether it works in our high-volume scenarios.  I this these are clues:

* https://github.com/Blizzard/node-rdkafka/pull/1081/files#diff-e574f6617d5a1bd9fb35fab6b02e906b120024e0dcae87b010eed716e23820d4R312-R319
* https://kafka.apache.org/documentation/#consumerconfigs_partition.assignment.strategy

**Comment by busma13** [comment]
`kafka_reader`, `kafka_sender`, and `kafka_dead_letter` all have configs with a `partition_assignment_strategy` field. We will need to update the types to allow for `cooperative-sticky`. We will also need to update the `schema.partition_assignment_strategy.format` array for each.

Then we just need to update each operation in a job to set the `partition_assignment_strategy` if applicable.

**Comment by busma13** [comment]
`partition_assignment_strategy` should not be in the sender or dead_letter, so we will be removing them.
ref: #873
